# docker-compose.scale.yml
version: '3.8'
services:
  web:
    image: nginx:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - loadbalance

  loadbalancer:
    image: haproxy:latest
    ports:
      - "80:80"
    configs:
      - source: haproxy_config
        target: /usr/local/etc/haproxy/haproxy.cfg
    networks:
      - loadbalance

configs:
  haproxy_config:
    file: ./haproxy.simple.cfg

networks:
  loadbalance:
    driver: overlay
